name: Build for Linux
description: 'Build V8 for Linux'

inputs:
  target-arch:
    description: 'Target Architecture'
    default: x64
    required: true

runs:
  using: "composite"
  steps:
    - name: Restore CCache
      uses: actions/cache@v5
      with:
        path: .ccache
        key: ${{ runner.os }}-${{ runner.arch }}-${{ inputs.target-arch }}:libv8:ccache:${{ github.run_number }}
        restore-keys: |
          ${{ runner.os }}-${{ runner.arch }}-${{ inputs.target-arch }}:libv8:ccache:
          ${{ runner.arch == 'X64' && format('{0}-{1}:libv8:ccache:', runner.os, inputs.target-arch) || '' }}

    - name: Setup Python
      uses: actions/setup-python@v6
      with:
        python-version: '3.11'

    - name: Setup Build Tools
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install -yq build-essential ccache curl git jq ninja-build python3 wget xz-utils pkg-config
        sudo update-ccache-symlinks

        echo "/usr/lib/ccache" >> "$GITHUB_PATH"

        ccacheDir="${GITHUB_WORKSPACE}/.ccache"
        test -d "$ccacheDir" || mkdir "$ccacheDir"

        echo "CCACHE_DIR=$ccacheDir" >> "$GITHUB_ENV"

    - name: Install native ARM64 toolchains
      if: ${{ runner.arch == 'ARM64' }}
      shell: bash
      run: bash deps/setup-linux-arm64.sh

    - name: Download V8 Source
      shell: bash
      working-directory: ./deps
      run: ./v8_download.sh

    - name: Prepare ARM64 sysroot
      shell: bash
      if: ${{ inputs.target-arch == 'arm64' }}
      working-directory: ./deps/v8
      run: |
        if [ "$(uname -m)" != aarch64 ]; then
          sudo apt-get install -yq g++-aarch64-linux-gnu
        fi
        build/linux/sysroot_scripts/install-sysroot.py --arch=arm64

    - name: Compile V8
      shell: bash
      working-directory: ./deps
      run: ./v8_compile.sh ${{ inputs.target-arch }}

    - name: Show CCache Status
      shell: bash
      working-directory: ./deps
      run: ccache -s
