name: Native Linux packages

on:
  workflow_call:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  platform:
    strategy:
      fail-fast: false
      matrix:
        include:
          - arch: x64
            runner: ubuntu-24.04
            platform: linux_amd64
            libc: glibc
          - arch: arm64
            runner: ubuntu-24.04-arm
            platform: linux_arm64
            libc: glibc
          - arch: x64
            runner: ubuntu-24.04
            platform: linux_musl_amd64
            libc: musl
          - arch: arm64
            runner: ubuntu-24.04-arm
            platform: linux_musl_arm64
            libc: musl
    uses: ./.github/workflows/native-platform.yml
    with:
      arch: ${{ matrix.arch }}
      runner: ${{ matrix.runner }}
      platform: ${{ matrix.platform }}
      libc: ${{ matrix.libc }}
